name: Build and Test

on:   
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-sdir:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build

    - name: Load MLIR cache
      uses: actions/cache@v2
      with:
        path: llvm-project
        key: ${{ runner.os }}-mlir

    - name: Build & Test
      run: |
        mkdir build
        cd build
        cmake -G Ninja .. -DLLVM_BUILD_DIR=${{github.workspace}}/llvm-project/build
        cmake --build . --target check-sdir

      
