name: check-sdir

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja

    - name: Build & Test
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target check-sdir

      
