name: check-sdir

on: push

jobs:
  Build and Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update

    - name: Build MLIR
      run: |
        sudo apt-get update
        git clone https://github.com/llvm/llvm-project
        mkdir llvm-project/build
        cd llvm-project/build
        cmake -G Ninja ../llvm -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="host" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON
        cmake --build . --target-mlir 
        cd ${{github.workspace}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja

    - name: Build & Test
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target check-sdir

      
