name: check-sdir

on: push

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build

    - name: Build MLIR
      run: |
        git clone https://github.com/llvm/llvm-project
        mkdir llvm-project/build
        cd llvm-project/build
        cmake -G Ninja ../llvm -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="host" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON
        cmake --build . --target-mlir 

    - name: Build & Test
      run: |
        mkdir build
        cd build
        cmake -G Ninja ..
        cmake --build . --target check-sdir

      
